---
title: "Environmental effects on harp seal reproduction in the NW Atlantic"
author: "adb"
bibliography: PG_ReproductivePaper.bib   ## bibliographic library. Place in same folder as .Rmd
date: "`r format(Sys.time(), '%d %B, %Y')`"
# bibliography: GAMS.bib   ## bibliographic library. Place in same folder as .Rmd
theme: jekyll-theme-slate
output:
  html_document:
    collapsed: no
    fig_caption: yes
    highlight: tango
    number_sections: yes
    smooth_scroll: yes
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('kableExtra')
library('grid')
library('plotly')

options(scipen = 999)
options(warn=-1)

# source(paste0(here::here(), "/analysis/leo.r"))

```


This short document provides details on the work carried out to assess environmental effects on reproductive parameters of harp seals in the Northwest Atlantic.     
This document is intended for internal use of the Fisheries and Oceans Canada team.       
Project led by Garry Stenson and Shelley Lang. 

Code and environemntal data to reproduce the analyses summarized in this document can be found in [**this repository**](https://github.com/adbpatagonia/PG_ReproductivePaper).     
Seal and prey field data will not be made available in the repository


# Questions                


# Data      

## Biological data        

### Population size        

Garry (or Shelley) to provide

### Female reproductive data            

Shelley to provide     


### Age data       

Shelley to provide   

### Morphometric data       

Shelley to provide   

          

## Prey field      

Garry requested capelin data from Aaron.            
Garry to contact MKA to request *Boreogadus*, shrimp, and sandlance indices from the fall survey         

## Environmental Indices         

### Newfoundland and Labrador Climate Index            

Downloaded    

 @Cyr2020: https://doi.org/10.20383/101.0301                 
 
 
### NAO            


Hurrell NAO Index  (DJFM)

https://climatedataguide.ucar.edu/sites/default/files/2023-07/nao_station_djfm.txt     

https://climatedataguide.ucar.edu/climate-data/hurrell-north-atlantic-oscillation-nao-index-station-based


### Arctic Oscillation      

ADB to download from  https://psl.noaa.gov/data/climateindices/list/  

### Atlantic Multidecadal Oscillation         

For the capelin paper (Buren et al 2014) we used the 121-month smoothed estimates      

The AMO was based on the Kaplan SST, but the dataset is not being updated anymore.  
https://psl.noaa.gov/data/timeseries/AMO/   

Therefore, I downloaded a few different options: 

1. Kaplan, unsmoothed: data/environment/AMO/amon.us.data.txt    
https://psl.noaa.gov/data/correlation/amon.us.data         
Data up to 2022        
2. Kaplan, smoothed: data/environment/AMO/amon.sm.data      
https://psl.noaa.gov/data/correlation/amon.sm.data     
Data up to Jan 2018. Maybe because of the smoothing this is a shorter time series?   
3. NOAA/NCEI has a time-series of the AMO based on the NOAA ERSSTV5: data/environment/AMO/ersst.v5.amo.dat.txt    
https://www1.ncdc.noaa.gov/pub/data/cmb/ersst/v5/index/ersst.v5.amo.dat   
Data up to July 2024     



Which one should we use?     
ADB to plot files 2 and 3 and compare        
Independently of which time series to use, we should probably use the 121-month smoother. From the AMO code, I understand that the smoother is simply a running average    
https://www.ncl.ucar.edu/Applications/Scripts/index_amo_1.ncl

 

### Ice Area Cover                

Downloaded from Canadian Ice Service    

https://iceweb1.cis.ec.gc.ca/IceGraph/page1.xhtml?lang=en


# Methods                      
# Results               

# References            
